/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WorkspacePlan = IDL.Variant({
  'pro' : IDL.Null,
  'free' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminGetUserWorkspacePlan' : IDL.Func(
      [IDL.Principal],
      [WorkspacePlan],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWorkspacePlan' : IDL.Func([], [WorkspacePlan], ['query']),
  'getUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'selectWorkspacePlan' : IDL.Func([WorkspacePlan], [], []),
  'setUsername' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WorkspacePlan = IDL.Variant({ 'pro' : IDL.Null, 'free' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminGetUserWorkspacePlan' : IDL.Func(
        [IDL.Principal],
        [WorkspacePlan],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWorkspacePlan' : IDL.Func([], [WorkspacePlan], ['query']),
    'getUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'selectWorkspacePlan' : IDL.Func([WorkspacePlan], [], []),
    'setUsername' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };